# serverless.yml

service: trufflehog-notifier

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: main.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2

functions:
  app:
    handler: wsgi.handler
    description: A simple app to send trufflehog notifications to slack
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'